name: Publish

permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: 'https://npm.pkg.github.com'

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Set npm access
        run: echo -e "\n//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ./.npmrc

      - run: npm publish
